modules:
  autominer: true
  tokens: true
  ranks: true
  enchants: true
  pickaxe:
    pickaxe-levels: true

database-type: sqlite
mysql:
  host: localhost
  port: 3306
  database: database
  username: root
  password: password

pickaxes-supported:
  - "DIAMOND_PICKAXE"